# Location of top-level MicroPython directory
MPY_DIR = ../..

# Name of module
MOD = adpcm

# Source files (.c or .py)
SRC = adpcm.c

# Architecture to build for (x86, x64, armv6m, armv7m, xtensa, xtensawin, rv32imc)
ARCH = xtensawin

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk
