# Location of top-level MicroPython directory
MPY_DIR = ../..

# Name of module
MOD = dec726

# Source files (.c or .py)
SRC = dec726.c g726_16.c g72x.c


# Architecture to build for (x86, x64, armv6m, armv7m, xtensa, xtensawin, rv32imc)
ARCH = xtensawin

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk

